version: '3.9'

services:
  user_db:
    image: postgres:18.0-alpine
    container_name: user_db
    restart: always
    environment:
      POSTGRES_DB: innoshop_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d innoshop_users"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  product_db:
    image: postgres:18.0-alpine
    container_name: product_db
    restart: always
    environment:
      POSTGRES_DB: innoshop_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d innoshop_products"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  user_service:
    build:
      context: .
      dockerfile: src/UserService/UserService.Presentation/Dockerfile
    container_name: user_service_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5195
      ConnectionStrings__DefaultConnection: Host=user_db;Port=5432;Database=innoshop_users;Username=postgres;Password=postgres
    ports:
      - "5195:5195"
    networks:
      - app_network
    depends_on:
      user_db:
        condition: service_healthy
  
  product_service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product_service_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5126
      ConnectionStrings__DefaultConnection: Host=product_db;Port=5432;Database=innoshop_products;Username=postgres;Password=postgres
    ports:
      - "5126:5126"
    networks:
      - app_network
    depends_on:
      product_db:
        condition: service_healthy

volumes:
  postgres_user_data:
  postgres_product_data:

networks:
  app_network:
    driver: bridge
